import random

ACTIVITIES = [
    # Animals
    ("Animals 🐾", "Pet a cat while it purrs"),
    ("Animals 🐾", "Hug a friendly dog"),
    ("Animals 🐾", "Watch kittens playing"),
    ("Animals 🐾", "Watch puppies discovering snow"),
    ("Animals 🐾", "Feed ducks at a pond"),
    ("Animals 🐾", "See a baby panda roll around"),
    ("Animals 🐾", "Foster a rescue animal"),
    ("Animals 🐾", "Watch goats jumping around"),
    ("Animals 🐾", "Let a dog rest its head on your lap"),
    ("Animals 🐾", "Watch a cat knead a blanket"),
    ("Animals 🐾", "Watch a dog greeting its owner"),
    ("Animals 🐾", "Look at baby animal photos"),
    ("Animals 🐾", "Visit an animal shelter"),
    ("Animals 🐾", "Feed a stray cat"),
    ("Animals 🐾", "Watch slow-motion puppy runs"),
    ("Animals 🐾", "Watch animal rescue videos"),
    ("Animals 🐾", "Watch animals reunite with owners"),
    ("Animals 🐾", "Play fetch with a dog"),
    ("Animals 🐾", "Let a cat sit on your keyboard"),
    ("Animals 🐾", "Watch baby otters hold hands"),
    # Physical Touch
    ("Physical Touch 🤗", "Hug someone for 20 seconds"),
    ("Physical Touch 🤗", "Hold hands while walking"),
    ("Physical Touch 🤗", "Give someone a genuine pat on the back"),
    ("Physical Touch 🤗", "Sit shoulder-to-shoulder with a friend"),
    ("Physical Touch 🤗", "Get a massage"),
    ("Physical Touch 🤗", "Give someone a massage"),
    ("Physical Touch 🤗", "High-five someone after good news"),
    ("Physical Touch 🤗", "Rest your head on someone's shoulder"),
    ("Physical Touch 🤗", "Group hug after a success"),
    ("Physical Touch 🤗", "Cuddle during a movie"),
    ("Physical Touch 🤗", "Hug a parent"),
    ("Physical Touch 🤗", "Hug a sibling"),
    ("Physical Touch 🤗", "Hug a friend you haven't seen in a while"),
    ("Physical Touch 🤗", "Put your arm around someone"),
    ("Physical Touch 🤗", "Lean on someone while sitting"),
    ("Physical Touch 🤗", "Playfully bump shoulders"),
    ("Physical Touch 🤗", "Hold someone during a scary movie"),
    ("Physical Touch 🤗", "Give a reassuring touch on the arm"),
    ("Physical Touch 🤗", "Sit close while chatting"),
    ("Physical Touch 🤗", "Cuddle with a blanket and someone"),
    # Eye Contact & Emotional Connection
    ("Emotional Connection 💬", "Have a deep conversation"),
    ("Emotional Connection 💬", "Share a genuine smile with a stranger"),
    ("Emotional Connection 💬", "Tell someone a sincere compliment"),
    ("Emotional Connection 💬", "Say \"I appreciate you\""),
    ("Emotional Connection 💬", "Share childhood stories"),
    ("Emotional Connection 💬", "Look through old photos together"),
    ("Emotional Connection 💬", "Have a late-night talk"),
    ("Emotional Connection 💬", "Watch a sunset together"),
    ("Emotional Connection 💬", "Celebrate a small win together"),
    ("Emotional Connection 💬", "Ask someone about their dreams"),
    ("Emotional Connection 💬", "Say \"I'm proud of you\""),
    ("Emotional Connection 💬", "Tell someone you're grateful for them"),
    ("Emotional Connection 💬", "Share a meaningful memory"),
    ("Emotional Connection 💬", "Encourage someone going through stress"),
    ("Emotional Connection 💬", "Ask someone how they're really doing"),
    ("Emotional Connection 💬", "Express admiration for someone"),
    ("Emotional Connection 💬", "Comfort someone who is sad"),
    ("Emotional Connection 💬", "Celebrate someone's achievement"),
    ("Emotional Connection 💬", "Share an emotional moment"),
    ("Emotional Connection 💬", "Laugh about past memories"),
    # Laughter
    ("Laughter 😂", "Watch ridiculous animal memes"),
    ("Laughter 😂", "Send a funny meme to a friend"),
    ("Laughter 😂", "Laugh until your stomach hurts"),
    ("Laughter 😂", "Watch blooper reels"),
    ("Laughter 😂", "Watch wholesome prank videos"),
    ("Laughter 😂", "Tell terrible dad jokes"),
    ("Laughter 😂", "Do a silly dance"),
    ("Laughter 😂", "Share embarrassing stories"),
    ("Laughter 😂", "Try a \"don't laugh\" challenge"),
    ("Laughter 😂", "Watch comedy clips"),
    ("Laughter 😂", "Send a ridiculous voice note"),
    ("Laughter 😂", "Laugh at old childhood photos"),
    ("Laughter 😂", "Watch stand-up comedy"),
    ("Laughter 😂", "Watch wholesome internet fails"),
    ("Laughter 😂", "Send a funny gif"),
    ("Laughter 😂", "Try improvising jokes with friends"),
    ("Laughter 😂", "Watch people laughing uncontrollably"),
    ("Laughter 😂", "Make ridiculous nicknames"),
    ("Laughter 😂", "Play charades"),
    ("Laughter 😂", "Rewatch a funny cartoon"),
    # Music
    ("Music 🎵", "Sing along to music with friends"),
    ("Music 🎵", "Dance together"),
    ("Music 🎵", "Attend a concert"),
    ("Music 🎵", "Listen to nostalgic songs"),
    ("Music 🎵", "Play music with others"),
    ("Music 🎵", "Join a choir"),
    ("Music 🎵", "Hum a melody together"),
    ("Music 🎵", "Play rhythm games"),
    ("Music 🎵", "Clap along to music"),
    ("Music 🎵", "Share a meaningful song"),
    ("Music 🎵", "Make a playlist for someone"),
    ("Music 🎵", "Slow dance with someone"),
    ("Music 🎵", "Sing karaoke"),
    ("Music 🎵", "Jam with instruments"),
    ("Music 🎵", "Share headphones with someone"),
    ("Music 🎵", "Listen to music under the stars"),
    ("Music 🎵", "Dance in your living room"),
    ("Music 🎵", "Play nostalgic childhood songs"),
    ("Music 🎵", "Sing loudly in the car"),
    ("Music 🎵", "Watch live street musicians"),
    # Food & Shared Rituals
    ("Food & Rituals 🍽️", "Cook dinner together"),
    ("Food & Rituals 🍽️", "Bake cookies together"),
    ("Food & Rituals 🍽️", "Share dessert"),
    ("Food & Rituals 🍽️", "Make tea or coffee for someone"),
    ("Food & Rituals 🍽️", "Eat comfort food with friends"),
    ("Food & Rituals 🍽️", "Have a family dinner"),
    ("Food & Rituals 🍽️", "Feed someone a bite jokingly"),
    ("Food & Rituals 🍽️", "Go on a picnic"),
    ("Food & Rituals 🍽️", "Share street food"),
    ("Food & Rituals 🍽️", "Celebrate a birthday"),
    ("Food & Rituals 🍽️", "Bring breakfast in bed"),
    ("Food & Rituals 🍽️", "Try cooking a new recipe together"),
    ("Food & Rituals 🍽️", "Share ice cream"),
    ("Food & Rituals 🍽️", "Make pancakes together"),
    ("Food & Rituals 🍽️", "Eat around a campfire"),
    ("Food & Rituals 🍽️", "Cook for someone you love"),
    ("Food & Rituals 🍽️", "Bring snacks to friends"),
    ("Food & Rituals 🍽️", "Surprise someone with their favorite food"),
    ("Food & Rituals 🍽️", "Eat late-night snacks together"),
    ("Food & Rituals 🍽️", "Try a new restaurant together"),
    # Romance
    ("Romance 💕", "Go on a first date"),
    ("Romance 💕", "Plan a surprise date"),
    ("Romance 💕", "Have a candlelight dinner"),
    ("Romance 💕", "Watch a romantic movie"),
    ("Romance 💕", "Walk together holding hands"),
    ("Romance 💕", "Kiss your partner"),
    ("Romance 💕", "Hug your partner for a long time"),
    ("Romance 💕", "Cuddle in bed"),
    ("Romance 💕", "Slow dance together"),
    ("Romance 💕", "Rest your head on your partner's chest"),
    ("Romance 💕", "Spend time being physically intimate"),
    ("Romance 💕", "Share post-intimacy cuddling"),
    ("Romance 💕", "Talk together after intimacy"),
    ("Romance 💕", "Fall asleep cuddling"),
    ("Romance 💕", "Wake up and hug each other"),
    ("Romance 💕", "Take a shower together"),
    ("Romance 💕", "Write a love note"),
    ("Romance 💕", "Recreate your first date"),
    ("Romance 💕", "Say \"I love you\""),
    # Quiet & Peaceful
    ("Quiet Moments 🌿", "Walk in nature"),
    ("Quiet Moments 🌿", "Watch the stars"),
    ("Quiet Moments 🌿", "Sit around a campfire"),
    ("Quiet Moments 🌿", "Build a blanket fort"),
    ("Quiet Moments 🌿", "Watch rain from a window"),
    ("Quiet Moments 🌿", "Drink hot chocolate in winter"),
    ("Quiet Moments 🌿", "Take a quiet walk at night"),
    ("Quiet Moments 🌿", "Watch the sunrise"),
    ("Quiet Moments 🌿", "Take naps together"),
    ("Quiet Moments 🌿", "Sit quietly with someone you trust"),
    ("Quiet Moments 🌿", "Read together"),
    ("Quiet Moments 🌿", "Watch snowfall together"),
    ("Quiet Moments 🌿", "Relax on a couch with friends"),
    ("Quiet Moments 🌿", "Sit in silence comfortably"),
    ("Quiet Moments 🌿", "Share a quiet morning coffee"),
    ("Quiet Moments 🌿", "Watch waves at the beach"),
    ("Quiet Moments 🌿", "Relax under a tree"),
    ("Quiet Moments 🌿", "Journal about gratitude"),
    ("Quiet Moments 🌿", "Meditate with someone"),
    ("Quiet Moments 🌿", "Share peaceful silence"),
    # Acts of Kindness
    ("Acts of Kindness 💛", "Help someone carry groceries"),
    ("Acts of Kindness 💛", "Donate clothes"),
    ("Acts of Kindness 💛", "Volunteer at a shelter"),
    ("Acts of Kindness 💛", "Give someone a compliment"),
    ("Acts of Kindness 💛", "Surprise someone with coffee"),
    ("Acts of Kindness 💛", "Leave a positive review"),
    ("Acts of Kindness 💛", "Write a thank-you note"),
    ("Acts of Kindness 💛", "Help a friend move"),
    ("Acts of Kindness 💛", "Pay for someone's coffee"),
    ("Acts of Kindness 💛", "Cheer someone up with a message"),
    ("Acts of Kindness 💛", "Hold the door for someone"),
    ("Acts of Kindness 💛", "Help someone learn something"),
    ("Acts of Kindness 💛", "Support a friend's project"),
    ("Acts of Kindness 💛", "Send an encouraging message"),
    ("Acts of Kindness 💛", "Leave a kind comment online"),
    ("Acts of Kindness 💛", "Help someone who is lost"),
    ("Acts of Kindness 💛", "Give someone flowers"),
    ("Acts of Kindness 💛", "Bring food to a sick friend"),
    ("Acts of Kindness 💛", "Encourage someone's dream"),
    ("Acts of Kindness 💛", "Thank someone sincerely"),
    # Digital Warmth
    ("Digital Warmth 📱", "Send someone a wholesome meme"),
    ("Digital Warmth 📱", "Watch \"humans being bros\" videos"),
    ("Digital Warmth 📱", "Watch surprise reunion videos"),
    ("Digital Warmth 📱", "Watch grandparents meeting babies"),
    ("Digital Warmth 📱", "Watch rescue animals recover"),
    ("Digital Warmth 📱", "Scroll through wholesome comments"),
    ("Digital Warmth 📱", "Send a \"thinking of you\" message"),
    ("Digital Warmth 📱", "Send a random compliment"),
    ("Digital Warmth 📱", "Share a cute animal video"),
    ("Digital Warmth 📱", "Send someone a song that reminds you of them"),
    ("Digital Warmth 📱", "Send a \"you're awesome\" text"),
    ("Digital Warmth 📱", "Send a random heart emoji"),
    ("Digital Warmth 📱", "Tell someone you appreciate them"),
    ("Digital Warmth 📱", "Send a wholesome TikTok"),
    ("Digital Warmth 📱", "Share a childhood memory"),
    ("Digital Warmth 📱", "Tell someone they made your day better"),
    ("Digital Warmth 📱", "Send a good-morning message"),
    ("Digital Warmth 📱", "Send a good-night message"),
    ("Digital Warmth 📱", "Remind someone they matter"),
    ("Digital Warmth 📱", "Tell someone \"I'm glad you exist\""),
]


def get_random_activity() -> tuple[str, str]:
    """Return a random (category, activity) tuple."""
    return random.choice(ACTIVITIES)
