services:
  - type: web
    name: oxytocin-bot
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
